#!/bin/bash

#this script exorts the mapper settings to /media/internal/mappersettings.xml
#made for PVJ 2.0

sudo cp /media/internal/mappersettings.xml /home/pi/of_v0.8.4/addons/ofxPiMapper/example/bin/data/surfaces.xml